[versions]
agp = "8.9.3"
appcompatV7 = "28.0.0"
espressoCore = "3.0.2"
junit = "4.13.2"
kotlin = "2.1.10"
kotlinVersion = "2.0.20"
runner = "1.0.2"

[libraries]
appcompat-v7 = { group = "com.android.support", name = "appcompat-v7", version.ref = "appcompatV7" }
espresso-core = { group = "com.android.support.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
runner = { group = "com.android.support.test", name = "runner", version.ref = "runner" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }

# Project Plugins
buildConfig = { id = "org.pointyware.gradle.buildconfig" }
