name: "CI/CD Release All Plugins"

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.11.1'

      - name: Build and Test
        run: |
          ./gradlew :build-config:publishMavenPublicationToProject

      - name: Sign and Publish Plugins
        env:
#          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
#          GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
        run: |
          ./gradlew :build-config:signAndUpload
